import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "sonner";
import Footer from "@/components/Footer";

const inter = Inter({
  variable: "--font-intner",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CarHub",
  description: "Generated by create next app",
     icons: {
    icon: "/model-icon.png"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}  h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <main>
          <Header />
          {children}
        <Footer />
        </main>
        <Toaster />
      </body>
    </html>
  );
}
